version: '3'
services:
  ruby:
    build:
      context: .
    stdin_open: true
    tty: true
    environment:
      - SLACK_API_TOKEN
    volumes:
      - .:/app
      - bundle_data:/usr/local/bundle
volumes:
  bundle_data:
    driver: local
